CREATE DATABASE youdemy;

USE youdemy;

CREATE TABLE role{
  id_role INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  
}

CREATE TABLE utilisateur{
  id_user INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(255) NOT NULL,
  prenom VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL, 
  id_role INT NOT NULL,
  FOREIGN KEY (id_role) REFERENCES role(id_role)
}

CREATE TABLE cours{
  id_cours INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  article VARCHAR(255) NOT NULL,
  video VARCHAR(255) NOT NULL
}

CREATE TABLE catigorie{
  id_cat INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(255) NOT NULL
}

CREATE TABLE tag{
  id_tag INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(255) NOT NULL
}

CREATE TABLE commentaire{
  id_comm INT NOT NULL PRIMARY AUTO_INCREMENT,
  comment VARCHAR(255) NOT NULL
}
